# Generated by Django 4.2.7 on 2023-11-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='brand_images/'),
        ),
    ]
